---
- name: Create user
  user:
    name: "{{ admin_user.name }}"
    password: "{{ admin_user.password | password_hash('sha512') }}"
    update_password: on_create
    state: present
    generate_ssh_key: "{{ admin_user.generate_ssh_key }}"
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
    home: "{{ admin_user.homedir }}"
    update_password: on_create

- name: Read public_key
  command: cat {{ admin_user.homedir }}/.ssh/id_rsa.pub
  register: public_key
  changed_when: false
  check_mode: no

- name: Write authorized_keys
  lineinfile:
    path: "{{ admin_user.homedir }}/.ssh/authorized_keys"
    line: "{{ public_key.stdout }}"
    owner: "{{ admin_user.name }}"
    group: "{{ admin_user.name }}"
    mode: 0600
    create: yes

- name: Write additional keys
  lineinfile:
    path: "{{ admin_user.homedir }}/.ssh/authorized_keys"
    line: "{{ item }}"
  with_items: "{{ admin_user.additional_ssh_keys }}"
